### ISSUE TITLE
[Question] What exactly is the point of this mod?

### ISSUE THREAD

**Issue by Apollounknowndev** [mohsenemx/CommandBlocksInCreative#1]
You can already access these blocks in the creative inventory if you have Operator Utilities enabled in your settings.

**Comment by naomieow** [comment]
this ^

**Comment by mohsenemx** [comment]
yes, but this makes your life easier!

**Comment by Apollounknowndev** [comment]
How, though? The tab already exists in vanilla, and with more blocks in it like the Light blocks and the normally unobtainable Painting variants.

**Comment by mohsenemx** [comment]
what if user doesn't have Operator Utilities?
`+` that requires OP, what if you don't have OP but you are creative?

**Comment by mohsenemx** [comment]
bold of you to assume that I know wtf I'm doing

**Comment by Apollounknowndev** [comment]
Fair enough.
